/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.felipecuervo.lab2;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.codec.binary.Base64;


/**
 *
 * @author lcuer
 */
public class PrincipalView extends javax.swing.JFrame {
    
  
    String selectEncrypt;
    
    

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textToEncrypt = new javax.swing.JTextArea();
        encrypt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selector = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sumArray = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inputNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        outNumber = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        numberAppear = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        userNumber = new javax.swing.JLabel();
        countTimes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userNumberReflect = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputArray = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        encryptText = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        decryptText = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        arrayOutCheck = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        realSolutionEncrypt = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        inArrayValueOut = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        realSolutionDecrypt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Encrypted Text ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 166, -1));

        textToEncrypt.setColumns(20);
        textToEncrypt.setRows(5);
        jScrollPane1.setViewportView(textToEncrypt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 290, 180));

        encrypt.setText("Encrypt Base 64");
        encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptActionPerformed(evt);
            }
        });
        getContentPane().add(encrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Decrypted Text");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 101, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Encrypter / Decrypter   Base64");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 358, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Integer list Array ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 331, -1));

        selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "1", "4", "6", "87", "43", "56" }));
        selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorActionPerformed(evt);
            }
        });
        getContentPane().add(selector, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 137, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel5.setText("Choose the array length");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("The sumatory of the random array is:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 221, -1));

        sumArray.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        sumArray.setText("          ");
        getContentPane().add(sumArray, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 110, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel10.setText("choose a number between 0 and 100");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 218, -1));

        inputNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNumberActionPerformed(evt);
            }
        });
        getContentPane().add(inputNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 96, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("the number that you typed (");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, -1, -1));

        outNumber.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        outNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(outNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 448, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setText(") in the array, appears:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, -1, -1));

        numberAppear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        numberAppear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(numberAppear, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 448, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setText("times");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 36, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("Create array");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 104, -1));

        userNumber.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        userNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(userNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 425, -1, -1));

        countTimes.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        countTimes.setText("    ");
        getContentPane().add(countTimes, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, 23, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("The randomize array list is: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 202, -1));

        userNumberReflect.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        userNumberReflect.setText("       ");
        getContentPane().add(userNumberReflect, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, -1, -1));

        outputArray.setColumns(20);
        outputArray.setRows(5);
        jScrollPane2.setViewportView(outputArray);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, -1, -1));

        jScrollPane3.setViewportView(encryptText);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 390, 37));

        jScrollPane4.setViewportView(decryptText);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 390, 34));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Encrypt moving array");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 120, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Encrypt base 64");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 100, 20));

        arrayOutCheck.setText("Encrypt");
        arrayOutCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrayOutCheckActionPerformed(evt);
            }
        });
        getContentPane().add(arrayOutCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, 20));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, -1, 20));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 40, -1));

        realSolutionEncrypt.setColumns(20);
        realSolutionEncrypt.setRows(5);
        jScrollPane5.setViewportView(realSolutionEncrypt);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 130, 60));

        jLabel16.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel16.setText("Encrypt /  Decrypt moving array ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        inArrayValueOut.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(inArrayValueOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 80, 30));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, -1, -1));

        realSolutionDecrypt.setColumns(20);
        realSolutionDecrypt.setRows(5);
        jScrollPane6.setViewportView(realSolutionDecrypt);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 120, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptActionPerformed
        // TODO add your handling code here:
        String encodeText,decodeText;
        String text = textToEncrypt.getText();
        
        byte[] encode = Base64.encodeBase64(text.getBytes());
        byte[] decode = Base64.decodeBase64(encode);
        
        encodeText=new String(encode);
        decodeText=new String(decode);
        
        encryptText.setText(encodeText);
        decryptText.setText(decodeText);
    }//GEN-LAST:event_encryptActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String textNumber = inputNumber.getText();
        String a="";
        int selectEncryptToInt;
        int intNumber=Integer.parseInt(textNumber);
        int sumOut=0;
        int flag=0;
        int i=0;
        int randNum;
        selectEncryptToInt=Integer.parseInt(selectEncrypt);
        userNumberReflect.setText(textNumber);
        
        String[] callArray =new String[selectEncryptToInt];
        
        for(i=0;i<selectEncryptToInt;i++){
         randNum = (int) (Math.random()*100);
          callArray=new String[selectEncryptToInt];
          callArray[i]=String.valueOf(randNum);
          
          if(intNumber == randNum){
          flag=flag+1;
          }

          a = a+"\n"+String.valueOf(randNum);
          System.out.println(a);
          outputArray.setText(a);
          
          
          sumOut=sumOut+randNum;

          }
        
 
        
       
        sumArray.setText(String.valueOf(sumOut));
        countTimes.setText(String.valueOf(flag));

    
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorActionPerformed
        // TODO add your handling code here:
        selectEncrypt=selector.getSelectedItem().toString();
        
    }//GEN-LAST:event_selectorActionPerformed

    private void inputNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumberActionPerformed

    private void arrayOutCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrayOutCheckActionPerformed
        String texto=textToEncrypt.getText();
        String getValue=inArrayValueOut.getText();
        String encryptOut="";
        String decryptOut="";
        int getValueInt=Integer.parseInt(getValue); 
        //System.out.println(getValueInt);
        char[] encryptChar = texto.toCharArray();
        char[] decryptChar = texto.toCharArray();

          for(char c : encryptChar){
        c+=getValueInt;
        
        String encryptString =Character.toString(c);
        encryptOut=encryptOut+" "+encryptString;
        System.out.print(encryptOut);
        realSolutionEncrypt.setText(encryptOut);
        
        }
        
        for(char c : encryptChar){
        c+=0;
        
        String decryptString=Character.toString(c);
        decryptOut=decryptOut+" "+decryptString;
        System.out.print(c);
        realSolutionDecrypt.setText(decryptOut);
        
        
        }
        
      
        
        
    }//GEN-LAST:event_arrayOutCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arrayOutCheck;
    private javax.swing.JLabel countTimes;
    private javax.swing.JTextPane decryptText;
    private javax.swing.JButton encrypt;
    private javax.swing.JTextPane encryptText;
    private javax.swing.JTextField inArrayValueOut;
    private javax.swing.JTextField inputNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel numberAppear;
    private javax.swing.JLabel outNumber;
    private javax.swing.JTextArea outputArray;
    private javax.swing.JTextArea realSolutionDecrypt;
    private javax.swing.JTextArea realSolutionEncrypt;
    private javax.swing.JComboBox<String> selector;
    private javax.swing.JLabel sumArray;
    private javax.swing.JTextArea textToEncrypt;
    private javax.swing.JLabel userNumber;
    private javax.swing.JLabel userNumberReflect;
    // End of variables declaration//GEN-END:variables
}
